#!/bin/bash

#need gtf and fa files for indexing
echo Make SURE FILES HAVE APPROPRIATE EXTENSIONS
read -e -p 'Please select gtf file directory for indexing: ' GTF_FILE
read -e -p 'Please select fa file directory for indexing: ' FA_FILE

#check to see if the files are correct
if [[ $GTF_FILE == *.gtf || $FA_FILE == *.fa ]]
then
    #files are accepted and will continue through HISAT2 processing
    mkdir index_files
    hisat2_extract_splice_sites.py $GTF_FILE > ./index_files/splicesites.tsv
    hisat2_extract_exons.py $GTF_FILE > ./index_files/exons.tsv
    read -p 'How many threads?: ' thrd
    hisat2-build -p $thrd --ss ./index_files/splicesites.tsv --exon ./index_files/exons.tsv $FA_FILE ./index_files/index     
else
    exit 'FILES COULD NOT BE READ'
fi
