#!/bin/bash

# This script is for alignment visualization

# Index the .bam files to create .bam.bai
read -e -p 'Select directory to folder containing .bam files (DO NOT SELECT .BAM FILE): ' BDIR
cd $BDIR
find *bam -exec echo samtools index {} \; | sh

# Can now use the IGV tool to visualize the .bam files

# This code is for bam read counting which is used to count the number
cd ..
mkdir bam_readcount
cd bam_readcount
read -e -p 'Select file directory for reference fasta: ' REF_FASTA
samtools faidx $REF_FASTA

# Then run mpileup tool to check for variance in a region
# Edit as needed (can have multiple bam files)
read -p 'Select region of interest (ex. chr:start-end): ' RI
samtools mpileup -f $REF_FASTA -r $RI path/to/file.bam

